use ratatui::text::Line;

pub const HELP_LINES: &[&str] = &[
    "Navigation",
    "  j / k / Down / Up     move selection",
    "  PageUp / PageDown     scroll by page",
    "  g / G                 top / bottom",
    "  h / l / ← / →         previous / next sprint or backlog",
    "  Tab / Shift+Tab       next / previous sprint or backlog",
    "",
    "Board",
    "  s                     sort (per tab, session only)",
    "  f                     filter (per tab, session only)",
    "  /                     search current tab (session only)",
    "  r                     refresh",
    "  Enter                 view issue",
    "  n                     create issue",
    "  e                     edit issue",
    "  d                     delete issue",
    "  a                     assign",
    "  t                     transition",
    "  m                     move to sprint / backlog",
    "",
    "Issue detail",
    "  Tab / Shift+Tab       next / previous section",
    "  PageUp / PageDown     scroll section by half page",
    "  p                     open parent",
    "  Enter                 open selected child",
    "  c                     create child",
    "  e                     edit issue (change parent)",
    "",
    "Create / edit",
    "  parent field          Enter to search (Epic for stories;",
    "                        required for sub-tasks; hidden for epics)",
    "",
    "Login",
    "  Enter                 log in with Atlassian (opens the browser)",
    "  Ctrl+o                open the generated Atlassian login link",
    "",
    "Commands",
    "  :logout               revoke tokens and return to login",
    "  :login                re-run authorization",
    "  :project              change project / board",
    "  :quit / :q            quit",
    "  ?                     toggle this help",
    "  Esc                   close overlay / go back",
    "  q                     quit (stays logged in)",
];

pub fn help_lines() -> Vec<Line<'static>> {
    HELP_LINES.iter().copied().map(Line::from).collect()
}
